---
name: Cleanup
on:
  schedule:
    # run every day
    - cron: "0 0 * * *"

jobs:
  clean:
    name: Clean stale packages and caches
    timeout-minutes: 5

    strategy:
      fail-fast: false
      matrix:
        go-version:
          - 1.14.x
          - 1.15.x
        os: [ubuntu-latest]
        may-fail: [false]
        include:
          - go-version: tip
            os: ubuntu-latest
            may-fail: true

    continue-on-error: ${{ matrix.may-fail }}
    runs-on: ${{ matrix.os }}

    env:
      GOFLAGS: -v -mod=readonly

    steps:
      - name: Set up Go ${{ matrix.go-version }}
        uses: percona-platform/setup-go@v2.1.2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out code into the Go module directory
        uses: percona-platform/checkout@v2.3.2
        with:
          lfs: true

      - name: Enable Go modules cache
        uses: percona-platform/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ matrix.os }}-go-${{ matrix.go-version }}-modules-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ matrix.os }}-go-${{ matrix.go-version }}-modules-

      - name: Enable Go build cache
        uses: percona-platform/cache@v2
        with:
          path: ~/.cache/go-build
          key: ${{ matrix.os }}-go-${{ matrix.go-version }}-build-${{ github.ref }}-${{ hashFiles('**') }}
          restore-keys: |
            ${{ matrix.os }}-go-${{ matrix.go-version }}-build-${{ github.ref }}-
            ${{ matrix.os }}-go-${{ matrix.go-version }}-build-

      - name: Collect stale package versions
        env:
          ROBOT_TOKEN: ${{ secrets.ROBOT_TOKEN }}
        uses: percona-platform/get-stale-packages-action@SAAS-255-Package-Get-Stale-Packages

      - name: Clean stale packages
        if: env.STALE_VERSIONS
        uses: percona-platform/delete-package-versions@v1.0.2
        with:
          package-version-ids: ${{ env.STALE_VERSIONS }}

      - name: Clean Go modules cache
        run: go clean -modcache
